### ISSUE TITLE
Getting error trying to run it

### ISSUE THREAD

**Issue by nikivdev** [egoist/dropcode#11]
Ran `pnpm i`. Then I get:

```
pnpm tauri dev

> dropcode@0.0.0 tauri /Users/nikiv/clones/dropcode
> tauri "dev"

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by egoist** [comment]
Weird, can you show the backtrace?

> run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by nikivdev** [comment]
ok so my rust wasn't installed, working now 🎊

**Comment by nikivdev** [comment]
@egoist 

<img width="642" alt="image" src="https://user-images.githubusercontent.com/6391776/200925352-3622e8aa-a6d8-4f0b-8b75-21236faef054.png">

Do you know what I should do after this? It just wrote finished but process didn't quit nor do I have a window spawned anywhere with Dropcode.

**Comment by egoist** [comment]
maybe try that again, the dropcode icon should appear in the dock 🤔

**Comment by nikivdev** [comment]
On Discord, [they say that window wasn't spawned because `show_main_window` didn't run](https://discord.com/channels/616186924390023171/731495028677148753/1039990372052512860).

Not sure why.

**Comment by nikivdev** [comment]
Oh ok it does show, my bad. It was old Dropcode app open that was production build. Ok going to try some code changes. :)
