### ISSUE TITLE
Is there way to open Dropcode SolidJS code to develop in browser

### ISSUE THREAD

**Issue by nikivdev** [egoist/dropcode#12]
I want to run Dropcode front end code as part of normal web dev so go to http://localhost:3000 and then any change I make in `src` will be hot reloaded.

Would be very nice to have. I had this setup with https://wails.io but new to Tauri so not sure.

**Comment by egoist** [comment]
The code is already hot reloaded when you make changes, the dev server (powered by Vite) is started at http://localhost:1420 when you run `pnpm tauri dev`

**Comment by nikivdev** [comment]
Beauty, thanks. Interesting choice with port number.
