### ISSUE TITLE
Unable to create a new snippet

### ISSUE THREAD

**Issue by aditya-67** [egoist/dropcode#6]
Unable to create a new snippet. Please find the video below 

https://user-images.githubusercontent.com/9695866/199229805-7d8f5ed5-7224-4013-a5b0-f5784b0dc675.mov

Is there any specific format for these snippets? Cuz I have a few `.ts`, `.txt` files already present in the folder but they are not showing up.

Am I missing something here?

**Comment by egoist** [comment]
Is your snippets folder stored in something like google drive? I haven't tested those, I've updated the app to track errors, please try the new version.

> Is there any specific format for these snippets? Cuz I have a few .ts, .txt files already present in the folder but they are not showing up.

Currently you can only create snippets from within the app, other files will not be recognized by it

**Comment by fdterr** [comment]
+1 Also having this issue. I was trying to store in a folder on my desktop

**Comment by mathuie** [comment]
+1.  Tried in my ~/code directory and also tried `~/Downloads`.  Didn't get a popup to allow permissions.

**Comment by Jackeriss** [comment]
+1

**Comment by egoist** [comment]
This should be fixed on v0.0.5
