### ISSUE TITLE
support for more languages (Ruby)

### ISSUE THREAD

**Issue by ZainW** [egoist/dropcode#7]
Great product,

unfortunatly i need something like this for ruby files (.rb), tried forking it and using the appropriate codemirror legacy packages but was unable to do this

happy to sponser for this support let me know if you have a $ amount for this support

**Comment by TPei** [comment]
Seconded! Would love Ruby support :)

**Comment by TPei** [comment]
Could this be done by adding `@codemirror/legacy-modes/mode/ruby`? 
Looks like this needs to go to the `package.json` and the `language.ts` 🤔

**Comment by egoist** [comment]
> Could this be done by adding `@codemirror/legacy-modes/mode/ruby`? Looks like this needs to go to the `package.json` and the `language.ts` 🤔

yeah, that's the solution

**Comment by egoist** [comment]
Released in 0.0.6: https://github.com/egoist/dropcode/releases/latest
