### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by kleenkanteen** [egoist/dropcode#8]

**Comment by lega0208** [comment]
Releases don't include Windows builds unfortunately, but I was able to build it for Windows from source. The build initially failed, complaining about a missing icon (src-tauri/icons/icon.ico), so I added a random icon of a toaster, and then seemed to build fine. It gave an error regarding an icon again at the end, but only after the build completed successfully, so not entirely sure what that was about.

In either case, it seems to be working fine for me. I put it up on my [Google Drive](https://drive.google.com/file/d/1ckFQjet9FqXBG871SiRnX3TbDfRvz-uv/view?usp=sharing) for anyone who doesn't feel like building from source. **Although** keep in mind that I'm some random guy on the internet, so I could have potentially added a cryptominer or something and you would have no way of really knowing. I didn't, but that's also what I would say if I did 😅
So I guess, for those who don't mind taking that risk, it's there for you to download at your leisure.

**Comment by rishabh1811** [comment]
> In either case, it seems to be working fine for me. I put it up on my [Google Drive](https://drive.google.com/file/d/1ckFQjet9FqXBG871SiRnX3TbDfRvz-uv/view?usp=sharing) for anyone who doesn't feel like building from source. **Although** keep in mind that I'm some random guy on the internet, so I could have potentially added a cryptominer or something and you would have no way of really knowing. I didn't, but that's also what I would say if I did 😅 So I guess, for those who don't mind taking that risk, it's there for you to download at your leisure.

Lol 😂

**Comment by egoist** [comment]
some changes are also required to make vscode snippet integration work on windows. will publish a windows release later 👌🏼

**Comment by egoist** [comment]
Windows release (.msi) is available now: https://github.com/egoist/dropcode/releases/latest
