### ISSUE TITLE
“Dropcode.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by kn0wn** [egoist/dropcode#9]
I recently updated to Ventura (Definitely a mistake)

"This software needs to be updated. Contact the developer for more information."

System;
Model Name: MacBook Pro
Chip: Apple M1 Pro
Memory: 16 GB
MacOS: 13.0 (22A380)

**Comment by egoist** [comment]
Weird, they all work fine for me, also on Ventura (M1)

**Comment by kn0wn** [comment]
Interesting, is there any other debug info I could get?

**Comment by egoist** [comment]
ok i guess the app has to be notarized, currently it's only signed but not notarized

**Comment by egoist** [comment]
Fixed https://github.com/egoist/dropcode/releases/tag/v0.0.7
